"""add is_notable and youtube_channel_id to users

Revision ID: 1f7aa2e58a0f
Revises: ab756eaf0463
Create Date: 2026-08-22 18:57:24.381297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f7aa2e58a0f'
down_revision: Union[str, Sequence[str], None] = 'ab756eaf0463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # is_notable is NOT NULL; server_default 'false' backfills existing user rows
    # (without it, adding a NOT NULL column to a populated table fails).
    op.add_column('users', sa.Column('is_notable', sa.Boolean(), nullable=False,
                                     server_default=sa.text('false')))
    op.add_column('users', sa.Column('youtube_channel_id', sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'youtube_channel_id')
    op.drop_column('users', 'is_notable')
    # ### end Alembic commands ###
