"""add fighter flag and country to ufc_fights

Revision ID: 267da4fa44f2
Revises: b7e2d14a8c35
Create Date: 2026-09-12 22:59:08.796744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267da4fa44f2'
down_revision: Union[str, Sequence[str], None] = 'b7e2d14a8c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add each corner's flag image and country name.

    ufc.com carries both on every bout already — a flag <img> and a country
    label per corner — in markup the scraper walked past on its way to the
    headshots.

    The flag URL is stored rather than an ISO code rendered as an emoji: flag
    emoji have no glyphs in the Windows emoji font, so Chrome and Edge there
    would show bare letters instead of a flag. An <img> renders identically
    everywhere, and img_a/img_b already hotlink this same CDN for headshots —
    one approach for both beats two.

    Nullable, no backfill: existing rows stay NULL and fill in as the scraper
    next visits each event. The UI renders nothing where they are unknown.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ufc_fights', sa.Column('flag_a', sa.String(), nullable=True))
    op.add_column('ufc_fights', sa.Column('flag_b', sa.String(), nullable=True))
    op.add_column('ufc_fights', sa.Column('country_a', sa.String(), nullable=True))
    op.add_column('ufc_fights', sa.Column('country_b', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop flags and countries — they vanish from the card."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ufc_fights', 'country_b')
    op.drop_column('ufc_fights', 'country_a')
    op.drop_column('ufc_fights', 'flag_b')
    op.drop_column('ufc_fights', 'flag_a')
    # ### end Alembic commands ###
