"""room covers and cover reports

Revision ID: 74e833026630
Revises: 75c8f7e117f8
Create Date: 2026-10-10 02:45:34.964443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e833026630'
down_revision: Union[str, Sequence[str], None] = '75c8f7e117f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_cover_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cover_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_room_cover_reports_one_per_user')
    )
    op.create_index(op.f('ix_room_cover_reports_group_id'), 'room_cover_reports', ['group_id'], unique=False)
    op.create_index(op.f('ix_room_cover_reports_user_id'), 'room_cover_reports', ['user_id'], unique=False)
    op.add_column('groups', sa.Column('cover_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'cover_url')
    op.drop_index(op.f('ix_room_cover_reports_user_id'), table_name='room_cover_reports')
    op.drop_index(op.f('ix_room_cover_reports_group_id'), table_name='room_cover_reports')
    op.drop_table('room_cover_reports')
    # ### end Alembic commands ###
