"""fighter bios

Revision ID: 75c8f7e117f8
Revises: a2cf199262c6
Create Date: 2026-10-06 00:33:33.263381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c8f7e117f8'
down_revision: Union[str, Sequence[str], None] = 'a2cf199262c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fighter_bios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fighter_norm', sa.String(), nullable=False),
    sa.Column('fighter', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('fights_at_generation', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fighter_bios_fighter_norm'), 'fighter_bios', ['fighter_norm'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fighter_bios_fighter_norm'), table_name='fighter_bios')
    op.drop_table('fighter_bios')
    # ### end Alembic commands ###
