"""event comments and votes

Revision ID: a2cf199262c6
Revises: 267da4fa44f2
Create Date: 2026-09-14 02:59:18.192650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2cf199262c6'
down_revision: Union[str, Sequence[str], None] = '267da4fa44f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['ufc_events.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['event_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_comments_feed', 'event_comments', ['event_id', 'parent_id', 'id'], unique=False)
    op.create_index(op.f('ix_event_comments_parent_id'), 'event_comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_event_comments_user_id'), 'event_comments', ['user_id'], unique=False)
    op.create_table('comment_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['event_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='uq_comment_votes_one_per_user')
    )
    op.create_index(op.f('ix_comment_votes_comment_id'), 'comment_votes', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_votes_user_id'), 'comment_votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_votes_user_id'), table_name='comment_votes')
    op.drop_index(op.f('ix_comment_votes_comment_id'), table_name='comment_votes')
    op.drop_table('comment_votes')
    op.drop_index(op.f('ix_event_comments_user_id'), table_name='event_comments')
    op.drop_index(op.f('ix_event_comments_parent_id'), table_name='event_comments')
    op.drop_index('ix_event_comments_feed', table_name='event_comments')
    op.drop_table('event_comments')
    # ### end Alembic commands ###
